import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import request from 'supertest';
import { AppModule } from '../../../src/app.module';
import { SubmissionResultDto } from '../../../src/modules/submission/dto/submission.response.dto';
import { TestcaseSample } from '../../../src/modules/problems/testcases/entities/testcase-sample.entity';
import { Problem } from '../../../src/modules/problems/entities/problem.entity';
import { DifficultyLevel } from '../../../src/modules/problems/enums/difficulty-level.enum';
import { DataSource } from 'typeorm';
import { EventSource } from 'eventsource';

describe('SubmissionController (e2e)', () => {
  let app: INestApplication;
  let moduleFixture: TestingModule;
  let baseUrl: string;
  let dataSource: DataSource;

  beforeAll(async () => {
    moduleFixture = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    await app.init();

    // Start app on an ephemeral port to allow EventSource to connect via HTTP URL
    await app.listen(0);
    baseUrl = await app.getUrl();

    dataSource = app.get(DataSource);
  });

  afterAll(async () => {
    if (app) {
      await app.close();
    }
    if (moduleFixture) {
      await moduleFixture.close();
    }
  });

  it('POST /submissions/run → stream result (Accepted) with real Judge0', async () => {
    // 1) Seed a Problem with two sample testcases (A+B)
    const problemRepo = dataSource.getRepository(Problem);

    const sample1 = Object.assign(new TestcaseSample(), {
      input: '1 2',
      output: '3',
    });
    const sample2 = Object.assign(new TestcaseSample(), {
      input: '42 58',
      output: '100',
    });

    const problem = problemRepo.create({
      title: 'Sum of Two Numbers (No-Mock E2E)',
      description: 'Read two integers and print their sum.',
      inputDescription: 'Two integers A and B separated by space.',
      outputDescription: 'The sum A+B.',
      maxScore: 100,
      timeLimitMs: 2000,
      memoryLimitKb: 256000,
      difficulty: DifficultyLevel.EASY,
      // relies on cascade: true in @OneToMany for TestcaseSample
      testcaseSamples: [sample1, sample2],
    });

    const savedProblem = await problemRepo.save(problem);
    expect(savedProblem.id).toBeDefined();
    expect(savedProblem.testcaseSamples?.length).toBe(2);

    // 2) Prepare real source code that should PASS both testcases
    // Using Python 3 (Judge0 often uses 71 for Python 3), adjust if needed.
    const languageId = 71;
    const sourceCode = `
import sys
data = sys.stdin.read().strip().split()
a, b = map(int, data[:2])
print(a + b)
`.trim();

    // 3) Initiate submission to your API (no mocks)
    const createRes = await request(app.getHttpServer())
      .post('/submissions/run')
      .send({
        languageId,
        sourceCode,
        problemId: savedProblem.id, // UUID generated by entity
        testCases: savedProblem.testcaseSamples.map(({ input, output }) => ({
          input,
          output,
        })),
      })
      .expect(201);

    const { submissionId } = createRes.body.data;
    expect(submissionId).toBeDefined();

    // 4) Connect to SSE stream (your service should poll Judge0 and emit "result")
    const finalResultPromise: Promise<SubmissionResultDto> = new Promise(
      (resolve, reject) => {
        const es = new EventSource(
          `${baseUrl}/submissions/${submissionId}/stream`,
        );

        const closeWith = (fn: (arg?: any) => void, arg?: any) => {
          try {
            es.close();
          } catch {}
          fn(arg);
        };

        es.addEventListener('result', (event: MessageEvent) => {
          try {
            const payload = JSON.parse(event.data);
            closeWith(resolve, payload);
          } catch (e) {
            closeWith(reject, e);
          }
        });

        es.onerror = (err) => {
          closeWith(reject, err);
        };
      },
    );

    // 5) Await final SSE result from your system (should be Accepted)
    const finalResult = await finalResultPromise;

    // 6) Assert final status
    expect(finalResult).toBeDefined();
    expect(finalResult.totalTests).toBe(2);

    // If your aggregation emits "Accepted" only when all pass:
    expect(finalResult.status).toMatch(/Accepted/i);

    // Optional if your payload contains counts:
    if (typeof finalResult.passedTests === 'number') {
      expect(finalResult.passedTests).toBe(2);
    }
  }, 60000); // Real end-to-end with Judge0 can take time; budget 60s
});
