import { Test, TestingModule } from '@nestjs/testing';
import { INestApplication } from '@nestjs/common';
import request from 'supertest';
import { EventSource } from 'eventsource';
import { AppModule } from '../../../src/app.module';
import { SubmissionResultDto } from '../../../src/modules/submission/dto/submission.result.dto';
import { TestcaseSample } from '../../../src/modules/problems/testcases/entities/testcase-sample.entity';
import { Problem } from '../../../src/modules/problems/entities/problem.entity';
import { DifficultyLevel } from '../../../src/modules/problems/enums/difficulty-level.enum';
import { DataSource } from 'typeorm';
import * as process from 'node:process';
import { SubmissionStatus } from '../../../src/modules/submission/enums/submission-status.enum';
import { SubmissionEvent } from '../../../src/modules/submission/enums/submission-event.enum';
import { initializeTransactionalContext } from 'typeorm-transactional';

describe('SubmissionController (e2e)', () => {
  let app: INestApplication;
  let moduleFixture: TestingModule;
  let dataSource: DataSource;
  const apiVersion: string = process.env.API_VERSION!;
  const appUrl: string = process.env.APP_URL!;
  const port: string = process.env.PORT!;

  beforeAll(async () => {
    initializeTransactionalContext();
    moduleFixture = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication();
    app.setGlobalPrefix(apiVersion);
    await app.init();

    // Start app on an ephemeral port to allow EventSource to connect via HTTP URL
    await app.listen(port);

    dataSource = app.get(DataSource);
  });

  afterAll(async () => {
    if (app) {
      await app.close();
    }
    if (moduleFixture) {
      await moduleFixture.close();
    }
  });

  it('POST /submissions/run → stream result (Accepted) with real Judge0', async () => {
    // 1) Seed a Problem with two sample testcases (A+B)
    const problemRepo = dataSource.getRepository(Problem);

    const sample1 = Object.assign(new TestcaseSample(), {
      input: '1 2',
      output: '3\n',
    });
    const sample2 = Object.assign(new TestcaseSample(), {
      input: '42 58',
      output: '100\n',
    });

    const problem = problemRepo.create({
      authorId: 1,
      title: 'Sum of Two Numbers (No-Mock E2E)',
      description: 'Read two integers and print their sum.',
      inputDescription: 'Two integers A and B separated by space.',
      outputDescription: 'The sum A+B.',
      maxScore: 100,
      timeLimitMs: 2000,
      memoryLimitKb: 256000,
      difficulty: DifficultyLevel.EASY,
      // relies on cascade: true in @OneToMany for TestcaseSample
      testcaseSamples: [sample1, sample2],
    });

    const savedProblem = await problemRepo.save(problem);
    expect(savedProblem.id).toBeDefined();
    expect(savedProblem.testcaseSamples?.length).toBe(2);

    // 2) Prepare real source code that should PASS both testcases
    // Using Python 3 (Judge0 often uses 71 for Python 3), adjust if needed.
    const languageId = 71;
    const sourceCode = `
import sys
data = sys.stdin.read().strip().split()
a, b = map(int, data[:2])
print(a + b)
`.trim();

    // 3) Initiate submission to your API (no mocks)
    const createRes = await request(app.getHttpServer())
      .post(`/${apiVersion}/submissions/run`)
      .send({
        languageId,
        sourceCode,
        problemId: savedProblem.id, // UUID generated by entity
        testCases: savedProblem.testcaseSamples.map(({ input, output }) => ({
          input,
          output,
        })),
      })
      .expect(201);

    const { submissionId } = createRes.body.data;
    expect(submissionId).toBeDefined();

    // 4) Connect to SSE stream
    const finalResultPromise: Promise<SubmissionResultDto> = new Promise(
      (resolve, reject) => {
        const url = `${appUrl}/${apiVersion}/submissions/${submissionId}/stream`;

        console.log(`Connecting to SSE stream at: ${url}`);
        const es = new EventSource(url);

        es.addEventListener(SubmissionEvent.RESULT, (event) => {
          try {
            es.close();
            const data = JSON.parse(event.data);
            resolve(data);
          } catch (e) {
            reject(e);
          }
        });

        es.onerror = (error) => {
          es.close();
          reject(new Error('SSE stream connection failed.'));
        };
      },
    );

    // 5) Await final SSE result
    const finalResult = await finalResultPromise;
    console.log(JSON.stringify(finalResult, null, 2));

    // 6) Assert final status
    expect(finalResult).toBeDefined();
    expect(finalResult.status).toBe(SubmissionStatus.ACCEPTED);
    expect(finalResult.totalTests).toBe(2);
    expect(finalResult.passedTests).toBe(2);

    // for sse browser testing -> click on the URL output in the console when debugging
    // await new Promise((r) => setTimeout(r, 5000));
  }, 60000);
});
